Controllers/ProductController.cs
using CloudDevelopment.Models;
using Microsoft.AspNetCore.Mvc;

namespace CloudDevelopment.Controllers;

public class ProductController : Controller
{
    public ProductTable prodtbl = new ProductTable();


    [HttpPost]
    public ActionResult InsertProducts(ProductTable products)
    {
        var result2 = prodtbl.insert_product(products);
        return RedirectToAction("Products", "Home");
    }

    [HttpGet]
    public ActionResult InsertProducts()
    {
        //return View(_productTable);
        return View();
    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using CloudDevelopment.Models;

namespace CloudDevelopment.Controllers;

public class UserController : Controller
{
    public UserTable usrtbl = new UserTable();



    [HttpPost]
    public ActionResult Privacy(UserTable Users)
    {
        var result = usrtbl.insert_User(Users);
        return RedirectToAction("Privacya", "Home");
    }

    [HttpGet]
    public ActionResult Privacy()
    {
        return View(usrtbl);
    }

    public IActionResult SignUp()
    {
        return View(); // This will make it visable on the webpage 
    }


}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CloudDev101</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CloudDev101.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CloudDev101</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About Us</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ContactUs">Contact Us</a>
                        </li>

                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="OurProducts">My Work Page</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacya">Privacy Ts & Cs </a>
                        </li>



                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login1 </a>
                        </li>




                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Orders">Orders</a>
                        </li>







                        <li class ="nav-item">
                            
                            <a class="nav-link text-dark" a asp-area="" asp-controller="User" asp-action="SignUp">Sign Up</a>
                        </li>



                        <li lass="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="InsertProducts">Insert Products</a>
                        </li>















                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CloudDev101 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>