Models/productTable.cs
/*using System.Data.SqlClient;

namespace CloudDevelopment.Models
{
    public class productTable
    {
        //public static string con_string = "Server=tcp:clouddev-sql-server.database.windows.net,1433;Initial Catalog=CLDVDatabase;Persist Security Info=False;User ID=Byron;Password=RockeyM12345;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30";
        public static string con_string = "Integrated Security=SSPI;Persist Security Info=False;User ID=\"\";Initial Catalog=test;Data Source=labVMH8OX\\SQLEXPRESS";

        public static SqlConnection con = new SqlConnection(con_string);

        public string Name { get; set; }

        public string Price { get; set; }

        public string Category { get; set; }

        public string Availability { get; set; }



        public int insert_product(productTable p)
        {

            try
            {
                string sql = "INSERT INTO productTable (productName, productPrice, productCategory, productAvailability) VALUES (@Name, @Price, @Category, @Availability)";
                SqlCommand cmd = new SqlCommand(sql, con);
                cmd.Parameters.AddWithValue("@Name", p.Name);
                cmd.Parameters.AddWithValue("@Price", p.Price);
                cmd.Parameters.AddWithValue("@Category", p.Category);
                cmd.Parameters.AddWithValue("@Availability", p.Availability);
                con.Open();
                int rowsAffected = cmd.ExecuteNonQuery();
                con.Close();
                return rowsAffected;
            }
            catch (Exception ex)
            {
                // Log the exception or handle it appropriately
                // For now, rethrow the exception
                throw ex;
            }


        }
    }
}*/ using System.Data.SqlClient;

namespace CloudDevelopment.Models;

public class ProductTable
{
    public static string ConString = "Server=tcp:clouddev-sql-server101.database.windows.net,1433;Initial Catalog=clod-sql-DB;Persist Security Info=False;User ID=Kashvir;Password=BrunoCorral1234#;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;";

    public static SqlConnection Con = new(ConString);


    public int ProductID { get; set; }

    public string productName { get; set; }

    public string Category { get; set; }

    public decimal Price { get; set; }

    public int Availability { get; set; }


    public int insert_product(ProductTable p)
    {
        try
        {
            const string sql = "INSERT INTO productTable (productName, Price, Category, Availability, ProductID) VALUES (@productName, @Price, @Category, @Availability, @ProductID)";
            var cmd = new SqlCommand(sql, Con);
            var random = new Random();
            var randomNumber = random.Next(1, 1001);
            cmd.Parameters.AddWithValue(@"ProductID", randomNumber);
            cmd.Parameters.AddWithValue("@productName", p.productName);
            cmd.Parameters.AddWithValue("@Price", p.Price);
            cmd.Parameters.AddWithValue("@Category", p.Category);
            cmd.Parameters.AddWithValue("@Availability", p.Availability);
            Con.Open();
            var rowsAffected = cmd.ExecuteNonQuery();
            Con.Close();
            return rowsAffected;
        }
        catch (Exception ex)
        {
            // Log the exception or handle it appropriately
            // For now, rethrow the exception
            throw ex;
        }
    }


    // Method to retrieve all products from the database
    public static List<ProductTable> GetAllProducts()
    {
        var products = new List<ProductTable>();

        using var con = new SqlConnection(ConString);
        const string sql = "SELECT * FROM productTable";
        var cmd = new SqlCommand(sql, con);

        con.Open();
        var rdr = cmd.ExecuteReader();
        while (rdr.Read())
        {
            var product = new ProductTable
            {
                ProductID = Convert.ToInt32(rdr["ProductID"]),
                productName = rdr["ProductName"].ToString(),
                Price = Convert.ToInt32(rdr["Price"]),
                Category = rdr["Category"].ToString(),
                Availability = Convert.ToInt32(rdr["Availability"])
            };

            products.Add(product);
        }

        return products;
    }
}

Controllers/HomeController.cs
//********************************* start of file ****************************//

using CloudDev101.Models;
using CloudDevelopment.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Transactions;

namespace CloudDev101.Controllers
{

    /// <summary>
    /// *Kashvir Sewpersad
    /// st10257503
    /// Kashclk31@gmail.com
    /// </summary>
    /// <returns></returns>






    public class HomeController(ILogger<HomeController> logger) : Controller
    {
        private readonly ILogger<HomeController> _logger = logger;

        public IActionResult Products(int userId)
        {
            var products = ProductTable.GetAllProducts();

            ViewData["Products"] = products;
            ViewData["UserID"] = userId;

            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult SignUp()
        {
            return View();
        }
        public IActionResult Orders()
        {
            var orders = Transactions.GetAllOrders();

            ViewData["Orders"] = orders;
            return View();
        }


        /*
         
         public class HomeController : Controller

        {

            private readonly ILogger<HomeController> _logger;

            public HomeController(ILogger<HomeController> logger)
            {
                _logger = logger;
            }


        */


        /*
        public IActionResult SignUp()
        {
            return View();
        }*/



        public IActionResult Index()
        {
            return View();
        }



        public IActionResult About()
        {
            return View(); // This will make it visable on the webpage 
        }


         
        public IActionResult Privacy()
        {
            return View();
        }



        public IActionResult ContactUs()
        {
            return View();
        }


        /*
         
         ourProducts is the "MyWork" page
         */

        public IActionResult OurProducts()
        {
            return View();
        }



        public IActionResult Privacya()
        {
            return View();
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }







    }
    
     





}
//************************************ end of file ***************************//

Controllers/LoginController.cs
using CloudDevelopment.Models;
using Microsoft.AspNetCore.Mvc;

namespace CloudDevelopment.Controllers
{
    public class LoginController : Controller
    {

        private readonly LoginModel _login;

        public LoginController()
        {
            
            _login = new LoginModel();

        }




        [HttpPost]
        public ActionResult Privacy(string email, string name)
        {
            var loginModel = new LoginModel();


            var userID = LoginModel.SelectUser(email, name);


            if (userID != -1)
            {

                //return RedirectToAction("Index", "Home", new { userID = userID });
                return RedirectToAction("Products", "Home", new { userID = userID });
            }


           
                
                return View("Index");
            
        }
    }
}

Controllers/ProductController.cs
using CloudDevelopment.Models;
using Microsoft.AspNetCore.Mvc;

namespace CloudDevelopment.Controllers;

public class ProductController : Controller
{
    public ProductTable prodtbl = new ProductTable();


    [HttpPost]
    public ActionResult InsertProducts(ProductTable products)
    {
        var result2 = prodtbl.insert_product(products);
        return RedirectToAction("Products", "Home");
    }

    [HttpGet]
    public ActionResult InsertProducts()
    {
        //return View(_productTable);
        return View();
    }
}

Controllers/TransactionController.cs
using CloudDevelopment.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using System.Data.SqlClient;

namespace CloudDev101.Controllers
{
    public class TransactionController : Controller
    {



        [HttpPost]
        public ActionResult PlaceOrder(int userID, int productID, int price)
        {
            try
            {
                var ConString = "Server=tcp:clouddev-sql-server101.database.windows.net,1433;Initial Catalog=clod-sql-DB;Persist Security Info=False;User ID=Kashvir;Password=BrunoCorral1234#;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;";
                Console.WriteLine(userID);
                Console.WriteLine(productID);
                var con = new SqlConnection(ConString);
                var sql =
                    "INSERT INTO Transactions (TransactionID, UserID, ProductID, TransactionDate, Quantity, TotalAmount) VALUES (@TransactionID, @UserID, @ProductID, @TransactionDate, @Quantity, @TotalAmount)";

                var cmd = new SqlCommand(sql, con);
                {
                    var random = new Random();
                    var randomNumber = random.Next(1, 1001);

                    cmd.Parameters.AddWithValue("@TransactionID", randomNumber);
                    cmd.Parameters.AddWithValue("@UserID", userID);
                    cmd.Parameters.AddWithValue("@ProductID", productID);
                    cmd.Parameters.AddWithValue("@TotalAmount", price);
                    cmd.Parameters.AddWithValue("Quantity", 1);
                    cmd.Parameters.AddWithValue("@TransactionDate", DateTime.Now);

                    con.Open();

                    var rowsAffected = cmd.ExecuteNonQuery();

                    con.Close();

                    if (rowsAffected > 0)
                        return RedirectToAction("Orders", "Home");
                    return View("Orders");
                }
            }
            catch (Exception ex)
            {
                
                Console.WriteLine(ex.Message);
                //Console.WriteLine(ex.StackTrace);
                return View("Error");
            }
        }
    }

}

Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using CloudDevelopment.Models;

namespace CloudDevelopment.Controllers;

public class UserController : Controller
{
    public UserTable usrtbl = new UserTable();



    [HttpPost]
    public ActionResult Privacy(UserTable Users)
    {
        var result = usrtbl.insert_User(Users);
        return RedirectToAction("Privacya", "Home");
    }

    [HttpGet]
    public ActionResult Privacy()
    {
        return View(usrtbl);
    }

    public IActionResult SignUp()
    {
        return View(); // This will make it visable on the webpage 
    }


}

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<br>

<h1 style="color : lightgoldenrodyellow; text-align :center"> About us 
    </h1>
<body class= "WebApp-BackgroundImage">

<p>

    <!--  This is a comment  -->

</p>
    <!---    <img src="~/Images/PotteryBackgound.jpg">    -->

    <div>

        <br>
        <br>

        <p style="color: navajowhite"> Welcome to KhumaloCraft, our little corner of handmade luxury! Founded in 2016, our small craft soap business was born out of a passion for natural ingredients and a desire to bring a touch of indulgence to everyday skincare routines.
            Nestled in the heart of South Africa, we pour our hearts and souls into each and every artisanal soap bar we create. At KhumaloCraft, we handcraft each bar with the finest botanicals and essential oils, ensuring a sensorial skincare experience.
            Our diverse fragrances cater to every mood, from soothing lavender to invigorating citrus.
            Beyond ingredients, we pride ourselves on meticulous attention to detail and sustainability.
            With eco-friendly packaging and a commitment to minimizing our environmental impact, we invite you to join us on a fragrant journey to healthier,
            happier skin—one handmade soap bar at a time.
        </p>

    </div>

  



    

</body>

Views/Home/ContactUs.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/Content/style.css">
</head>




<body>
   

  <!--  <form action="your_form_processing_page.html" method="post"> -->

        <div class="contact-form">

           <form >
               <div class="row">

                <div class="input-group">
                    <input type="text" id="name" required>
                    <label for="name"> Your Name</label>
                </div>
                <div class="input-group">
                    <input type="text" id="number" required>
                    <label for="number"> Phone.no</label>
                </div>

               </div>
              
                <div class="input-group">
                    <input type="email" id="email" required>
                    <label for="email">  Email id </label>
                </div>
                <div class="input-group">
                    <textarea id="message" rows="8" required></textarea>
                    <label for="name"> Your Message</label>
                    <br>
                    <button type="submit">  SUBMIT   </button>
                </div>
           </form>

            
        </div>
 <!--  </form> -->

    <footer class="footer">
      
    </footer>
</body>


</html>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
   <br>
    <br>
    <br>
    <br>
    <p class="privacy-policy">
        At KumaloCraft, our primary goal is to redefine luxury through handcrafted soap.
        We aspire to elevate the everyday cleansing ritual into a sensorial experience that indulges and rejuvenates.
        Our commitment to luxury begins with meticulously sourcing the finest natural ingredients, chosen for their nourishing properties and sustainability.
        Through our artisanal process, we blend these ingredients with care, infusing each bar with a harmonious balance of fragrance, texture, and skincare benefits.
        Our dedication to quality craftsmanship ensures that every bar is a masterpiece, worthy of adorning your bathroom counter.
    </p>
</div>

Views/Home/Login.cshtml
@model CloudDevelopment.Models.UserTable
@{
    ViewData["Title"] = "Login";
}

<div class="text-center">
    <h1>Login</h1>
    <p>
        If you do not already have an account, you may <a href="@Url.Action("SignUp", "User")">Register</a> for a new account by following the underlined link.
    </p>
</div>

<div class="container">
    <form asp-controller="Login" asp-action="Privacy" method="post">
        
        <p>Please enter both your first name and your email address:</p>
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" id="name" name="name" class="form-control" placeholder="Name" required>
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" id="email" name="email" class="form-control" placeholder="example@gmail.com" required>
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
    </form>
</div>

Views/Home/Orders.cshtml
@using CloudDevelopment.Models
@model int

@{
    ViewData["Title"] = "Orders";
    var orders = ViewData["Orders"] as List<Transactions>;
}

<div class="text-center">
    <h1>Orders</h1>
    <p>
        Please ensure that orders have been made prior to viewing this page. If the below
        table is empty, it is highly probable that no orders have yet to be made
    </p>
</div>


<h2>Order List:</h2>
<table style="color: white; " class="table">
    <thead>
        <tr>
            <th>TransactionID</th>
            <th>UserID</th>
            <th>ProductID</th>
            <th>TransactionDate</th>
            <th>Quantity</th>
            <th>TotalAmount</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var order in orders)
        {
            <tr>
                <td>@order.TransactionId</td>
                <td>@order.UserId</td>
                <td>@order.ProductId</td>
                <td>@order.TransactionDate</td>
                <td>@order.Quantity</td>
                <td>@order.TotalAmount</td>
            </tr>
        }
    </tbody>
</table>

Views/Home/OurProducts.cshtml
@{
    ViewData["Title"] = "OurProducts";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />



<body>


    <div class ="gallery">

      

        <div class="content">
            <img src="~/Images/Product1.png" />

            <h3>Handcrafted Goat Milk Soap</h3>

            <p>Goat milk soap is a natural skincare product made from a combination of goat's milk, oils, and lye. Renowned for its gentle and moisturizing properties, goat milk soap is suitable for all skin types, including sensitive and dry skin. </p>
            <h6>R100.00</h6>
                <ul>
                       <li><i class ="fa fa-star checked"></i></li>
                       <li><i class="fa fa-star checked"></i></li>
                       <li><i class="fa fa-star checked"></i></li>
                       <li><i class="fa fa-star checked"></i></li>
                       <li><i class="fa fa-star "></i></li>
                </ul>
                <button class="buy-1">Buy Now</button>

        </div>



        <div class="content">
             <img src="~/Images/Handwash.png" />

            <h3> Irresistible Hand Wash</h3>

            <p>Envelop yourself in a liquid embrace of purity,leaving hands feeling as though they've been caressed by silk.Infused with the finest ingredients,our handwash boasts a symphony of botanical extracts and nourishing oils,meticulously blended to indulge the senses and lavish your skin with unrivaled hydration. </p>

            <h6>R150.00</h6>
         <ul>
                <li><i class="fa fa-star checked"></i></li>
                <li><i class="fa fa-star checked"></i></li>
                <li><i class="fa fa-star checked"></i></li>
                <li><i class="fa fa-star "></i></li>
                <li><i class="fa fa-star "></i></li>
         </ul>
            <button class="buy-2">Buy Now</button>


     </div>

      <div class="content">

            <img src="~/Images/bubbles.png" />

            <h3>Delectable Bubble Bath</h3>

            <p>Immerse yourself in a world of tranquility and luxury with our indulgent bubble bath, a sanctuary of serenity awaiting your every dip. Crafted with the finest botanical extracts and essential oils, each drop of our bubble bath transforms your bathwater into a frothy oasis of relaxation. </p>
                <h6>R200.00</h6>
            <ul>
                    <li><i class="fa fa-star checked"></i></li>
                    <li><i class="fa fa-star checked"></i></li>
                    <li><i class="fa fa-star checked"></i></li>
                    <li><i class="fa fa-star "></i></li>
                    <li><i class="fa fa-star "></i></li>
            </ul>
        <button class="buy-3">Buy Now</button>

   
    </div>

  




    </div>
  


</body>

Views/Home/Privacya.cshtml
@{
    ViewData["Title"] = "";
}
<h1>@ViewData["Title"]</h1>
 <br>
<br>
<br>
<br>
<br>


<p class="privacy-policy">
    
    At our quaint soap shop, we highly value your privacy.
    Our privacy policy is designed to safeguard your personal information, ensuring it remains secure and confidential.
    We collect only necessary data for processing orders and improving your shopping experience, never sharing or selling it to third parties. Rest assured, your trust is paramount to us. For detailed information on how we handle your data, please refer to our privacy terms and conditions available on our website.
    Thank you for entrusting us with your privacy.</p>



   
    @model CloudDevelopment.Models.UserTable;
@{
    ViewData["Title"] = "Login";
}

<h1>@ViewData["Title"]</h1>

<div class="text-center">
    <h1 class="display-4">Login</h1>
    <p>If you don't have an account <a href="https://localhost:7277/User/About">Sign Up</a> for a new account.</p>
</div>

<body>
    <form asp-controller="User" asp-action="Privacy" method="post">
        <p>Please enter your first name and email:</p>
        <input type="text" name="name" placeholder="Name" required>
        <input type="text" name="surname" placeholder="Surname" required>
        <input type="text" name="email" placeholder="example@gmail.com" required>
        <button type="submit">Submit</button>
    </form>

</body>

Views/Home/Products.cshtml
@using CloudDevelopment.Models
@model int

@{
    ViewData["Title"] = "My Work";
    var userId = ViewData["userID"];
    var products = ViewData["Products"] as List<ProductTable>;
}


<div class="text-center">
    <h1>My Work</h1>
    <p>Please ensure that you have successfully logged in before attempting to place an order.</p>
    <p>If you are logged in you will see a UserID other than 0 displayed below.</p>
</div>

@if (userId != null)
{
    <p class="user-id-text">User ID: @userId</p>
}

<h2>Product List:</h2>

<table style="color: white; "class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Price</th>
            <th>Description</th>
            <th>QuantityInStock</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var product in products)
        {
            <tr>
                <td>@product.productName</td>
                <td>@product.Price</td>
                <td>@product.Category</td>
                <td>@product.Availability</td>
                <td>
                    <form asp-controller="Transaction" class="product-form" asp-action="PlaceOrder" method="post">
                        <input type="hidden" name="userID" value="@userId" />
                        <input type="hidden" name="productID" value="@product.ProductID" />
                        <input type="hidden" name="Price" value="@product.Price" />
                        <button class="product-button" type="submit"> Place Order </button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>